# syntax=docker.io/docker/dockerfile:1

FROM node:20-bullseye AS base
WORKDIR /app

FROM base AS deps
COPY package.json yarn.lock ./
RUN yarn

FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NODE_ENV
ARG PORT
ARG HOSTNAME
ARG BASE_URL
ARG CRYPTO_KEY
ARG GITHUB_APP_ID
ARG GITHUB_APP_CLIENT_ID
ARG GITHUB_APP_CLIENT_SECRET
ARG GITHUB_APP_PRIVATE_KEY
ARG GITHUB_APP_WEBHOOK_SECRET
ARG SQLITE_AUTH_TOKEN
ARG SQLITE_URL
ARG RESEND_API_KEY
ARG RESEND_DOMAIN_EMAIL

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV HOSTNAME=$HOSTNAME
ENV BASE_URL=$BASE_URL
ENV CRYPTO_KEY=$CRYPTO_KEY
ENV GITHUB_APP_ID=$GITHUB_APP_ID
ENV GITHUB_APP_CLIENT_ID=$GITHUB_APP_CLIENT_ID
ENV GITHUB_APP_CLIENT_SECRET=$GITHUB_APP_CLIENT_SECRET
ENV GITHUB_APP_PRIVATE_KEY=$GITHUB_APP_PRIVATE_KEY
ENV GITHUB_APP_WEBHOOK_SECRET=$GITHUB_APP_WEBHOOK_SECRET
ENV SQLITE_AUTH_TOKEN=$SQLITE_AUTH_TOKEN
ENV SQLITE_URL=$SQLITE_URL
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV RESEND_DOMAIN_EMAIL=$RESEND_DOMAIN_EMAIL

RUN echo "DEBUG (builder stage): SQLITE_URL=$SQLITE_URL"

RUN yarn build

FROM base AS runner
WORKDIR /app

ARG NODE_ENV
ARG PORT
ARG HOSTNAME
ARG BASE_URL
ARG CRYPTO_KEY
ARG GITHUB_APP_ID
ARG GITHUB_APP_CLIENT_ID
ARG GITHUB_APP_CLIENT_SECRET
ARG GITHUB_APP_PRIVATE_KEY
ARG GITHUB_APP_WEBHOOK_SECRET
ARG SQLITE_AUTH_TOKEN
ARG SQLITE_URL
ARG RESEND_API_KEY
ARG RESEND_DOMAIN_EMAIL

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV HOSTNAME=$HOSTNAME
ENV BASE_URL=$BASE_URL
ENV CRYPTO_KEY=$CRYPTO_KEY
ENV GITHUB_APP_ID=$GITHUB_APP_ID
ENV GITHUB_APP_CLIENT_ID=$GITHUB_APP_CLIENT_ID
ENV GITHUB_APP_CLIENT_SECRET=$GITHUB_APP_CLIENT_SECRET
ENV GITHUB_APP_PRIVATE_KEY=$GITHUB_APP_PRIVATE_KEY
ENV GITHUB_APP_WEBHOOK_SECRET=$GITHUB_APP_WEBHOOK_SECRET
ENV SQLITE_AUTH_TOKEN=$SQLITE_AUTH_TOKEN
ENV SQLITE_URL=$SQLITE_URL
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV RESEND_DOMAIN_EMAIL=$RESEND_DOMAIN_EMAIL

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

EXPOSE 1988
ENV PORT=1988
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
