# syntax=docker.io/docker/dockerfile:1

FROM node:23-bullseye AS base
WORKDIR /app

FROM base AS deps
COPY package.json ./
RUN npm install

FROM base AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NODE_ENV
ARG PORT
ARG HOSTNAME
ARG BASE_URL
ARG CRYPTO_KEY
ARG BETTER_AUTH_SECRET
ARG GITHUB_APP_ID
ARG GITHUB_APP_NAME
ARG GITHUB_APP_CLIENT_ID
ARG GITHUB_APP_CLIENT_SECRET
ARG GITHUB_APP_PRIVATE_KEY
ARG GITHUB_APP_WEBHOOK_SECRET
ARG DATABASE_URL
ARG EMAIL_FROM
ARG EMAIL_PROVIDER
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ARG ADMIN_EMAILS

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV HOSTNAME=$HOSTNAME
ENV BASE_URL=$BASE_URL
ENV CRYPTO_KEY=$CRYPTO_KEY
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV GITHUB_APP_ID=$GITHUB_APP_ID
ENV GITHUB_APP_NAME=$GITHUB_APP_NAME
ENV GITHUB_APP_CLIENT_ID=$GITHUB_APP_CLIENT_ID
ENV GITHUB_APP_CLIENT_SECRET=$GITHUB_APP_CLIENT_SECRET
ENV GITHUB_APP_PRIVATE_KEY=$GITHUB_APP_PRIVATE_KEY
ENV GITHUB_APP_WEBHOOK_SECRET=$GITHUB_APP_WEBHOOK_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV EMAIL_FROM=$EMAIL_FROM
ENV EMAIL_PROVIDER=$EMAIL_PROVIDER
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL
ENV ADMIN_EMAILS=$ADMIN_EMAILS

RUN npm run build

FROM base AS runner
WORKDIR /app

ARG NODE_ENV
ARG PORT
ARG HOSTNAME
ARG BASE_URL
ARG CRYPTO_KEY
ARG BETTER_AUTH_SECRET
ARG GITHUB_APP_ID
ARG GITHUB_APP_NAME
ARG GITHUB_APP_CLIENT_ID
ARG GITHUB_APP_CLIENT_SECRET
ARG GITHUB_APP_PRIVATE_KEY
ARG GITHUB_APP_WEBHOOK_SECRET
ARG DATABASE_URL
ARG EMAIL_FROM
ARG EMAIL_PROVIDER
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ARG ADMIN_EMAILS

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV HOSTNAME=$HOSTNAME
ENV BASE_URL=$BASE_URL
ENV CRYPTO_KEY=$CRYPTO_KEY
ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV GITHUB_APP_ID=$GITHUB_APP_ID
ENV GITHUB_APP_NAME=$GITHUB_APP_NAME
ENV GITHUB_APP_CLIENT_ID=$GITHUB_APP_CLIENT_ID
ENV GITHUB_APP_CLIENT_SECRET=$GITHUB_APP_CLIENT_SECRET
ENV GITHUB_APP_PRIVATE_KEY=$GITHUB_APP_PRIVATE_KEY
ENV GITHUB_APP_WEBHOOK_SECRET=$GITHUB_APP_WEBHOOK_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV EMAIL_FROM=$EMAIL_FROM
ENV EMAIL_PROVIDER=$EMAIL_PROVIDER
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV RESEND_FROM_EMAIL=$RESEND_FROM_EMAIL
ENV ADMIN_EMAILS=$ADMIN_EMAILS

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

EXPOSE 1988
ENV PORT=1988
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
