version: '3.8'

services:
  app:
    image: user/app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    secrets:
      - secrets
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

secrets:
  secrets:
    file: ./secrets.txt