name: Remote Docker Compose Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setting up SSH keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        tags: user/app:latest
        secrets: |
          "NODE_ENV=production"
          "PORT=3000"
          "HOSTNAME=0.0.0.0"
          "TURBO_REMOTE_ONLY=true"
          "TURBO_RUN_SUMMARY=true"
          "TURBO_DOWNLOAD_LOCAL_ENABLED=true"
          "NX_DAEMON=false"
          "TURBO_CACHE=remote:rw"
          "BASE_URL=https://cms.velaj.net"
          "CRYPTO_KEY=${{ secrets.CRYPTO_KEY }}"
          "GITHUB_APP_CLIENT_ID= ${{ secrets.APP_CLIENT_ID }}"
          "GITHUB_APP_CLIENT_SECRET=${{ secrets.APP_CLIENT_SECRET }}"
          "GITHUB_APP_ID=${{ secrets.APP_ID }}"
          "GITHUB_APP_NAME=edlir-velaj-cms"
          "GITHUB_APP_PRIVATE_KEY=${{ secrets.APP_PRIVATE_KEY }}"
          "GITHUB_APP_WEBHOOK_SECRET=${{ secrets.APP_WEBHOOK_SECRET }}"
          "SQLITE_AUTH_TOKEN=${{ secrets.SQLITE_AUTH_TOKEN }}"
          "SQLITE_URL=${{ secrets.SQLITE_URL }}"
          "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}"
    
    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no root@49.12.15.46 << 'ENDSSH'
        cd /var/www/cms
        git pull
        docker-compose build
        docker-compose -p cms up -d --build
        ENDSSH
     
