name: Remote Docker Compose Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setting up SSH keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Prepare secrets
      run: |
        mkdir -p /run/secrets
        echo "${{ secrets.CRYPTO_KEY }}" > /run/secrets/CRYPTO_KEY
        echo "${{ secrets.APP_CLIENT_ID }}" > /run/secrets/GITHUB_APP_CLIENT_ID
        echo "${{ secrets.APP_CLIENT_SECRET }}" > /run/secrets/GITHUB_APP_CLIENT_SECRET
        echo "${{ secrets.APP_ID }}" > /run/secrets/GITHUB_APP_ID
        echo "${{ secrets.APP_PRIVATE_KEY }}" > /run/secrets/GITHUB_APP_PRIVATE_KEY
        echo "${{ secrets.APP_WEBHOOK_SECRET }}" > /run/secrets/GITHUB_APP_WEBHOOK_SECRET
        echo "${{ secrets.SQLITE_AUTH_TOKEN }}" > /run/secrets/SQLITE_AUTH_TOKEN
        echo "${{ secrets.SQLITE_URL }}" > /run/secrets/SQLITE_URL
        echo "${{ secrets.RESEND_API_KEY }}" > /run/secrets/RESEND_API_KEY

    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/x86_64
        tags: user/app:latest
        secrets: |
          id=NODE_ENV,src=/run/secrets/NODE_ENV
          id=PORT,src=/run/secrets/PORT
          id=BASE_URL,src=/run/secrets/BASE_URL
          id=CRYPTO_KEY,src=/run/secrets/CRYPTO_KEY
          id=GITHUB_APP_CLIENT_ID,src=/run/secrets/GITHUB_APP_CLIENT_ID
          id=GITHUB_APP_CLIENT_SECRET,src=/run/secrets/GITHUB_APP_CLIENT_SECRET
          id=GITHUB_APP_ID,src=/run/secrets/GITHUB_APP_ID
          id=GITHUB_APP_PRIVATE_KEY,src=/run/secrets/GITHUB_APP_PRIVATE_KEY
          id=GITHUB_APP_WEBHOOK_SECRET,src=/run/secrets/GITHUB_APP_WEBHOOK_SECRET
          id=SQLITE_AUTH_TOKEN,src=/run/secrets/SQLITE_AUTH_TOKEN
          id=SQLITE_URL,src=/run/secrets/SQLITE_URL
          id=RESEND_API_KEY,src=/run/secrets/RESEND_API_KEY
    
    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no root@49.12.15.46 << 'ENDSSH'
        cd /var/www/cms
        git pull

        echo "production" > /run/secrets/NODE_ENV
        echo "3000" > /run/secrets/PORT
        echo "0.0.0.0" > /run/secrets/HOSTNAME
        echo "https://cms.velaj.net" > /run/secrets/BASE_URL
        echo "${{ secrets.CRYPTO_KEY }}" > /run/secrets/CRYPTO_KEY
        echo "${{ secrets.APP_ID }}" > /run/secrets/GITHUB_APP_ID
        echo "${{ secrets.APP_CLIENT_ID }}" > /run/secrets/GITHUB_APP_CLIENT_ID
        echo "${{ secrets.APP_CLIENT_SECRET }}" > /run/secrets/GITHUB_APP_CLIENT_SECRET
        echo "${{ secrets.APP_PRIVATE_KEY }}" > /run/secrets/GITHUB_APP_PRIVATE_KEY
        echo "${{ secrets.APP_WEBHOOK_SECRET }}" > /run/secrets/GITHUB_APP_WEBHOOK_SECRET
        echo "${{ secrets.SQLITE_AUTH_TOKEN }}" > /run/secrets/SQLITE_AUTH_TOKEN
        echo "${{ secrets.SQLITE_URL }}" > /run/secrets/SQLITE_URL
        echo "${{ secrets.RESEND_API_KEY }}" > /run/secrets/RESEND_API_KEY

        docker-compose pull
        docker-compose -p cms up -d --build
        ENDSSH
     
