name: Remote Docker Compose Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setting up SSH keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/x86_64
        tags: ghcr.io/degun/pages-cms:latest
        push: true
        build-args: |
          NODE_ENV=production
          PORT=3000
          HOSTNAME=0.0.0.0
          BASE_URL=https://cms.velaj.net
          CRYPTO_KEY=${{ secrets.CRYPTO_KEY }}
          GITHUB_APP_ID=${{ secrets.APP_ID }}
          GITHUB_APP_CLIENT_ID=${{ secrets.APP_CLIENT_ID }}
          GITHUB_APP_CLIENT_SECRET=${{ secrets.APP_CLIENT_SECRET }}
          GITHUB_APP_PRIVATE_KEY=${{ secrets.APP_PRIVATE_KEY }}
          GITHUB_APP_WEBHOOK_SECRET=${{ secrets.APP_WEBHOOK_SECRET }}
          SQLITE_AUTH_TOKEN=${{ secrets.SQLITE_AUTH_TOKEN }}
          SQLITE_URL=${{ secrets.SQLITE_URL }}
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
    
    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no root@49.12.15.46 << 'ENDSSH'
        cd /var/www/cms
        docker login ghcr.io -u degun -p ${{ secrets.TOKEN }}
        docker pull ghcr.io/degun/pages-cms:latest
        docker run -d --name cms --restart unless-stopped -p 3000:3000 ghcr.io/degun/pages-cms:latest
        ENDSSH
     
